import { apiService } from '../../../services/api';

export const dataprepApi = {
  createDatasetVersion: apiService.createDatasetVersion,
  createClassificationBalanceCheckpoint: apiService.createClassificationBalanceCheckpoint,
  createEvaluationFilterCheckpoint: apiService.createEvaluationFilterCheckpoint,
  createRefineAcceptCheckpoint: apiService.createRefineAcceptCheckpoint,
  updateDatasetVersionPrepareProgress: apiService.updateDatasetVersionPrepareProgress,
  getDatasetVersionDetail: apiService.getDatasetVersionDetail,
  deleteDatasetVersion: apiService.deleteDatasetVersion,
  deleteDatasetVersionItem: apiService.deleteDatasetVersionItem,
  updateDatasetVersionVisibility: apiService.updateDatasetVersionVisibility,
  updateDatasetVersionSharing: apiService.updateDatasetVersionSharing,
  getDatasetVersionAssignments: apiService.getDatasetVersionAssignments,
  getDatasetVersionUserAssignmentDetail: apiService.getDatasetVersionUserAssignmentDetail,
  getMyAssignmentSubmissionStatus: apiService.getMyAssignmentSubmissionStatus,
  submitMyAssignment: apiService.submitMyAssignment,
  approveAssignmentSubmission: apiService.approveAssignmentSubmission,
  assignDatasetVersionRange: apiService.assignDatasetVersionRange,
  clearDatasetVersionAssignmentRange: apiService.clearDatasetVersionAssignmentRange,
  clearDatasetVersionUserAssignments: apiService.clearDatasetVersionUserAssignments,
  getPublicProjectLabeling: apiService.getPublicProjectLabeling,
  getPublicProjectsHub: apiService.getPublicProjectsHub,
  getSampleLabels: apiService.getSampleLabels,
  addSampleLabel: apiService.addSampleLabel,
  voteSampleLabel: apiService.voteSampleLabel,
  previewMessageAutoLabels: apiService.previewMessageAutoLabels,
  saveMessageAutoLabels: apiService.saveMessageAutoLabels,
  previewAndSaveMessageAutoLabelsBatch: apiService.previewAndSaveMessageAutoLabelsBatch,
  previewAutoLabels: apiService.previewAutoLabels,
  saveAutoLabels: apiService.saveAutoLabels,
  clusterVersion: apiService.clusterVersion,
  clusterVersionFilter: apiService.clusterVersionFilter,
  clusterVersionRemoveNoise: apiService.clusterVersionRemoveNoise,
  clusterVersionDeduplicate: apiService.clusterVersionDeduplicate,
  clusterVersionVisualize: apiService.clusterVersionVisualize,
  deleteClusterCache: apiService.deleteClusterCache,
};

export type DataprepApi = typeof dataprepApi;
